services:
  haproxy:
    image: haproxy:2.5
    restart: always
    ports:
      - "7890:8000"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    command: "-c app.test=true" # -c log_statement=all

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    command: --requirepass password

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      # docker cp metatype-elastic-1:/usr/share/elasticsearch/config/certs/http_ca.crt .
      ELASTIC_PASSWORD: password
