services:
  haproxy:
    image: haproxy:2.5
    restart: always
    ports:
      - "7890:8000"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    command: "-c app.test=true" # -c log_statement=all

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    command: --requirepass password

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      # docker exec metatype-elastic-1 cat /usr/share/elasticsearch/config/certs/http_ca.crt | jq -sR .
      ELASTIC_PASSWORD: password

  minio:
    image: bitnami/minio:2022
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_REGION_NAME: local
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: 'bucket:none'

  imgproxy:
    image: darthsim/imgproxy:v3.9
    restart: always
    ports:
      - "9002:8080"
    environment:
      IMGPROXY_KEY: b80b429c37bb45810ce29669071e618da2a608dbeb734270630fec22516e57eefea06ffa7636cfa570625ceb9a5da50641706e6706bd8ca0e869cfcfd17e992c
      IMGPROXY_SALT: 17ae43716720df9f200f3aeaff058add690dff32ece50fec0dd30a1b18285dad2029362040cba8591f878f7a91f445f11598d2ac9a22a91b3645cb56ac942f10
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_MAX_SRC_RESOLUTION: "8"
      IMGPROXY_ENABLE_WEBP_DETECTION: "true"
      IMGPROXY_ENABLE_AVIF_DETECTION: "true"
      IMGPROXY_ENABLE_CLIENT_HINTS: "true"
      IMGPROXY_USE_S3: "true"
      IMGPROXY_S3_ENDPOINT: http://minio:9000
      IMGPROXY_ALLOWED_SOURCES: "s3://bucket/"
      IMGPROXY_ALLOW_ORIGIN: "http://localhost:3000"
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: local
