[tool.poetry]
name = "example"
version = "0.1.15-0+dev"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
typegraph = "0.1.15-0+dev"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
