services:
  typegate:
    image: ghcr.io/metatypedev/typegate:v0.0.3-dev.7
    platform: linux/amd64
    #build:
    #  context: ..
    #  dockerfile: dev/Dockerfile
    restart: always
    ports:
      - "7890:7890"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DEBUG: "true"
      REDIS_URL: redis://:password@redis:6379/0
      TG_SECRET: "a4lNi0PbEItlFZbus1oeH/+wyIxi9uH6TpL8AIqIaMBNvp7SESmuUBbfUwC0prxhGhZqHw8vMDYZAGMhSZ4fLw=="
      TG_ADMIN_PASSWORD: password
    env_file:
      - .env.sample
    depends_on:
      - redis

  redis:
    image: redis:7
    restart: always
    command: --requirepass password

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
