[tool.poetry]
name = "examples"
version = "0.0.3-dev.5"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
typegraph = { path = "../typegraph", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
