[package]
name = "native"
version = "0.0.1"
edition = "2021"

[lib]
name = "native"
crate-type = ["cdylib"]

[dependencies]
config = "0.13.1"
anyhow = "1.0"
deno_bindgen = "0.7.0"
serde = { version = "1.0.143", features = ["derive"] }
query-core = { git = "https://github.com/prisma/prisma-engines" }
query-connector = { git = "https://github.com/prisma/prisma-engines" }
request-handlers = { git = "https://github.com/prisma/prisma-engines" }
prisma-models = { git = "https://github.com/prisma/prisma-engines" }
datamodel = { git = "https://github.com/prisma/prisma-engines" }
user-facing-errors = { git = "https://github.com/prisma/prisma-engines" }
introspection-connector = { git = "https://github.com/prisma/prisma-engines" }
introspection-core = { git = "https://github.com/prisma/prisma-engines" }
sql-introspection-connector = { git = "https://github.com/prisma/prisma-engines" }
mongodb-introspection-connector = { git = "https://github.com/prisma/prisma-engines" }
connection-string = "0.1.14"
url = "2.2.2"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
lazy_static = "1.4.0"
log = "0.4.17"
env_logger = "0.9.0"
serde_json = "1.0.83"
dashmap = "5.3.4"
common = { path = "../../libs/common" }
sentry = "0.27.0"
static_init = "1.0.3"
