[package]
name = "native"
version = "0.0.2-alpha.13"
edition = "2021"

[lib]
name = "native"
crate-type = ["cdylib"]

[dependencies]
config = "0.13.3"
anyhow = "1.0"
deno_bindgen = "0.7.0"
serde = { version = "1.0.151", features = ["derive"] }
query-core = { git = "https://github.com/prisma/prisma-engines" }
query-connector = { git = "https://github.com/prisma/prisma-engines" }
request-handlers = { git = "https://github.com/prisma/prisma-engines" }
prisma-models = { git = "https://github.com/prisma/prisma-engines" }
datamodel-renderer = { git = "https://github.com/prisma/prisma-engines" }
user-facing-errors = { git = "https://github.com/prisma/prisma-engines" }
introspection-connector = { git = "https://github.com/prisma/prisma-engines" }
introspection-core = { git = "https://github.com/prisma/prisma-engines" }
sql-introspection-connector = { git = "https://github.com/prisma/prisma-engines" }
mongodb-introspection-connector = { git = "https://github.com/prisma/prisma-engines" }
migration-core = { git = "https://github.com/prisma/prisma-engines" }
migration-connector = { git = "https://github.com/prisma/prisma-engines" }
connection-string = "0.1.14"
url = "2.3.1"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["full"] }
lazy_static = "1.4.0"
log = "0.4.17"
env_logger = "0.10.0"
serde_json = "1.0.91"
dashmap = "5.4.0"
common = { path = "../../libs/common" }
sentry = "0.29.1"
static_init = "1.0.3"
tempfile = "3.3.0"
convert_case = "0.6.0"
rust-s3 = { git = "https://github.com/zifeo/rust-s3", branch = "order" }
http = "0.2.8"
uuid = { version = "1.2.2", features = ["v4"] }
