[package]
name = "typegraph_core"
version = "0.1.10"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
enum_dispatch = "0.3.11"
once_cell = "1.18.0"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.100"
# version has been bumped since python package wasmtime v9.0.0 does not
# support component version 3
wit-bindgen = "0.6.0"
regex = "1.9.0"
indexmap = { version = "1.9.3", features = ["serde"] }
common = { path = "../../libs/common" }
indoc = "2.0.2"

[dev-dependencies]
insta = { version = "1.30.0", features = ["glob"] }
pathdiff = "0.2.1"

[features]
wasm = []
