[package]
name = "typegraph_core"
version = "0.1.9-dev.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.70"
enum_dispatch = "0.3.11"
once_cell = "1.17.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
wit-bindgen = "0.6.0"

[features]
wasm = []
