[package]
name = "typegraph_core"
version = "0.1.13-0+dev"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
enum_dispatch = "0.3.12"
once_cell = "1.18.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
wit-bindgen = "0.9.0"
regex = "1.9.3"
# https://github.com/GREsau/schemars/pull/226
indexmap = { version = "=1.9.3", features = ["serde"] }
common = { path = "../../libs/common" }
indoc = "2.0.3"
graphql-parser = "0.4.0"
sha2 = "0.10.7"

[dev-dependencies]
insta = { version = "1.31.0", features = ["glob"] }
pathdiff = "0.2.1"

[features]
wasm = []
