[package]
name = "typegate_prod"
edition.workspace = true
version.workspace = true

[dependencies]
colored = "2.0.4"
envconfig = "0.10.0"
sentry = { version = "0.31.7", features = ["anyhow"] }
env_logger = "0.10.0"
log = "0.4.20"
typegate_core.workspace = true
common.workspace = true
